export type City = 
    "New York"
    | "Los Angeles" 
    | "London"
    | "Paris"
    | "Berlin"
    | "Moscow"
    | "Dubai"
    | "Tokyo"
    | "Beijing"
    | "Seoul"
    | "Sydney"
    | "São Paulo"
    | "Buenos Aires"
    | "Mexico City"
    | "Toronto"
    | "Cairo"
    | "Johannesburg"
    | "New Delhi"
    | "Bangkok"
    | "Singapore";